# Generated by Django 2.1 on 2019-07-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Open_Acc_App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_app', models.CharField(max_length=256)),
                ('currency', models.CharField(max_length=256)),
            ],
        ),
    ]
