# Generated by Django 2.1 on 2019-07-25 02:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_acc_app',
            name='app_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 25, 2, 55, 45, 11449, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='open_acc_app',
            name='reg_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='open_acc_app',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('JPY', 'JPY'), ('SGD', 'SGD'), ('CNY', 'CNY')], max_length=256),
        ),
        migrations.AlterField(
            model_name='open_acc_app',
            name='type_app',
            field=models.CharField(blank=True, choices=[('Current Account', 'Current Account'), ('Time Deposit', 'Time Deposit'), ('High Yield Demand Deposit Account', 'High Yield Demand Deposit Account')], max_length=256),
        ),
    ]
