# Generated by Django 2.1 on 2019-07-25 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_auto_20190725_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_acc_app',
            name='bank_acc_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='open_acc_app',
            name='biz',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='open_acc_app',
            name='bizNo',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='open_acc_app',
            name='dateof_incorp',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='open_acc_app',
            name='mail_add',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='open_acc_app',
            name='no_staff',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='open_acc_app',
            name='paidup_cap',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='open_acc_app',
            name='phoneNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='open_acc_app',
            name='placeof_incorp',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='open_acc_app',
            name='reg_add',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='open_acc_app',
            name='app_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
