# Generated by Django 2.1 on 2019-07-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_auto_20190725_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='open_acc_app',
            name='app_date',
        ),
        migrations.AlterField(
            model_name='open_acc_app',
            name='bank_acc_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='open_acc_app',
            name='biz',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='open_acc_app',
            name='bizNo',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='open_acc_app',
            name='dateof_incorp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='open_acc_app',
            name='mail_add',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='open_acc_app',
            name='no_staff',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='open_acc_app',
            name='paidup_cap',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='open_acc_app',
            name='phoneNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='open_acc_app',
            name='placeof_incorp',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='open_acc_app',
            name='reg_add',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='open_acc_app',
            name='type_app',
            field=models.CharField(choices=[('Current Account', 'Current Account'), ('Time Deposit', 'Time Deposit'), ('High Yield Demand Deposit Account', 'High Yield Demand Deposit Account')], max_length=256),
        ),
    ]
