# Generated by Django 2.1 on 2019-07-29 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_open_acc_app_type_of_biz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='open_acc_app',
            old_name='bank_acc_name',
            new_name='bank_account_name',
        ),
        migrations.RenameField(
            model_name='open_acc_app',
            old_name='biz',
            new_name='business_registration_No',
        ),
        migrations.RenameField(
            model_name='open_acc_app',
            old_name='dateof_incorp',
            new_name='date_of_incorporation',
        ),
        migrations.RenameField(
            model_name='open_acc_app',
            old_name='bizNo',
            new_name='mailing_address',
        ),
        migrations.RenameField(
            model_name='open_acc_app',
            old_name='mail_add',
            new_name='nature_of_business',
        ),
        migrations.RenameField(
            model_name='open_acc_app',
            old_name='no_staff',
            new_name='number_of_staff',
        ),
        migrations.RenameField(
            model_name='open_acc_app',
            old_name='paidup_cap',
            new_name='paidup_capital',
        ),
        migrations.RenameField(
            model_name='open_acc_app',
            old_name='placeof_incorp',
            new_name='place_of_incorporation',
        ),
        migrations.RenameField(
            model_name='open_acc_app',
            old_name='reg_add',
            new_name='registered_address',
        ),
        migrations.RenameField(
            model_name='open_acc_app',
            old_name='reg_name',
            new_name='registered_name',
        ),
        migrations.RenameField(
            model_name='open_acc_app',
            old_name='phoneNo',
            new_name='telephone_No',
        ),
        migrations.RenameField(
            model_name='open_acc_app',
            old_name='type_app',
            new_name='type_of_application',
        ),
        migrations.RenameField(
            model_name='open_acc_app',
            old_name='type_of_biz',
            new_name='type_of_business',
        ),
        migrations.AddField(
            model_name='open_acc_app',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
